"""Initial migration

Revision ID: b9ae7c23082d
Revises: 
Create Date: 2025-11-13 09:13:58.226191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ae7c23082d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=False),
    sa.Column('credits_received_total', sa.Integer(), nullable=False),
    sa.Column('monthly_sent_this_month', sa.Integer(), nullable=False),
    sa.Column('last_credit_reset', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_reset_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('carried_forward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('credits_redeemed', sa.Integer(), nullable=False),
    sa.Column('voucher_value_inr', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recognition_id', sa.Integer(), nullable=False),
    sa.Column('endorser_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endorser_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['recognition_id'], ['recognitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recognition_id', 'endorser_id', name='unique_recognition_endorser')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endorsements')
    op.drop_table('redemptions')
    op.drop_table('recognitions')
    op.drop_table('monthly_reset_logs')
    op.drop_table('students')
    # ### end Alembic commands ###
